apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-mysql.fullname" . }}
  labels:
    {{- include "chart-mysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart-mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart-mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: {{ .Values.service.port }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: root