apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-mysql.fullname" . }}
  labels:
    {{- include "chart-mysql.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "chart-mysql.selectorLabels" . | nindent 4 }}
