apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-frontend.fullname" . }}
  labels:
    {{- include "chart-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      name: frontend
  selector:
    {{- include "chart-frontend.selectorLabels" . | nindent 4 }}
