apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        service: frontend
    spec:
     containers:
     - name: frontend
       image: parmjailwal007/frontend:v3
       ports:
       - containerPort: 5000
