apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: parmjailwal007/sql-db:v3
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: employees_db
        - name: MYSQL_ROOT_PASSWORD
          value: root